# Generated by Django 3.2.13 on 2022-12-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInput', models.IntegerField(blank=True, null=True, verbose_name='Номер Входящий')),
                ('user', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Подпись пользователя')),
                ('nomenklatura', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номенклатура')),
            ],
        ),
        migrations.CreateModel(
            name='InputJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInput', models.IntegerField(blank=True, null=True, verbose_name='Номер Входящий')),
                ('correspondent', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Кореспондент (откуда поступило)')),
                ('content', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Краткое содержание')),
                ('datenumber', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дата и исходящий номер')),
                ('executor', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Исполнитель')),
                ('executionDate', models.DateField(blank=True, max_length=1000, null=True, verbose_name='Сроки исполнения')),
                ('mark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отметка об исполнении')),
                ('nomenklatura', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номенклатура')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal_dev.signature')),
            ],
        ),
    ]
