# Generated by Django 3.2.13 on 2023-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_dev', '0002_inputjournal_datereg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputjournal',
            name='dateReg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регисрации'),
        ),
    ]
