# Generated by Django 3.2.13 on 2023-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_dev', '0003_alter_inputjournal_datereg'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputjournal',
            name='dateTimeReg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время регисрации'),
        ),
        migrations.AlterField(
            model_name='inputjournal',
            name='dateReg',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регисрации'),
        ),
    ]
