# Generated by Django 3.2.13 on 2023-03-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_dev', '0004_auto_20230313_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputjournal',
            name='dateTimeReg',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время регисрации'),
        ),
    ]
