# Generated by Django 3.2.13 on 2023-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_dev', '0005_alter_inputjournal_datetimereg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputjournal',
            name='dateTimeReg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время регисрации'),
        ),
    ]
